language: node_js
node_js:
- '5.3'
script: "bin/t"
cache:
  directories:
    - node_modules
    - public/bower_components
notifications:
  email : false
services:
  - redis-server
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - mongodb-upstart
    - ubuntu-toolchain-r-test
    packages :
    - mongodb-org-server
    - g++-4.8
