language: node_js
node_js:
- '0.10'
script: "bin/t"
cache:
  directories:
    - node_modules
    - public/bower_components
notifications:
  email : false
services:
  - redis-server
  - mongodb
sudo: false
