#!/bin/sh -e
export PORT=3000
export PORTSSL=8000
export ENABLESSL=no
export SSL_HOSTNAME=localhost:8000
export HOSTNAME=localhost:3000
export SESSION_SECRET="lkj234usfd908nm234sdflk324"
export NODE_ENV=development
export MONGO="mongodb://localhost:27017/gala?auto_reconnect=true&maxPoolSize=10"
export REDIS="redis://localhost:6379/"
export ENABLE_DONATION="yes"
export ENABLE_REGISTRATION="yes"
export PP_HOST="api.sandbox.paypal.com"
export PP_PORT=""
export PP_CLIENT_ID=""
export PP_CLIENT_SECRET=""
export NOTIFICATION_EMAIL=""
export OCRYPTO=pass
export AWS_KEYID=""
export AWS_SECRET=""
export AWS_REGION="us-east-1"
